= Take a Pi Image 

We update our Pi image every 4-6 months to keep install times speedy. As part of an install, we update the Pi to make sure it has all the latest security patches, and the further it's been since we updated the image, the longer that update takes. The following is the process we follow to take an image.  

== Getting started
Download the lastest Raspbian image from https://www.raspberrypi.org/downloads/raspbian[the Raspberry Pi Foundation] and flash it onto an SD card. Before inserting the SD card into a Pi, it's helpful to create a file called `ssh` in the `boot`partition so that you can SSH into the Pi once it's plugged in. Once that's done, insert the SD card into the Pi, plug in a network cable, and insert the power cable to turn the Pi on.

Once the Pi is powered on, you'll be able to SSH into the Pi using the IP address that is printed a few lines above the login line. The default username is `pi` and the default password is `raspberry`.

== OS Setup
TIP: Most of these commmands require being root to run them. It's easiest to just become the root user by running `sudo su` when you start a new section.

=== Update the OS
[source,bash]
----
touch /boot/ssh # <1>
timedatectl set-timezone "America/Denver" # <2>

date -s "$(wget -qSO- --max-redirect=0 google.com 2>&1 | grep Date: | cut -d' ' -f5-8)Z" # <3>

apt update
apt -y upgrade
apt -y install vim
apt -y autoremove
apt -y autoclean

vim /etc/default/keyboard <4>

passwd pi <5>
usermod -aG sudo pi

vim /home/pi/.ssh/authorized_keys <6>

reboot
----
<1> Make sure SSH stays enabled
<2> Set the timezone to the appropriate timezone for yourself
<3> This command updates the default time
<4> Change `XKBLAYOUT` to `us`
<5> Change the default password to whatever password you want
<6> Copy any public ssh keys into this folder so that they can log into the pi without the password

=== Docker
First, install the docker engine.
[source,bash]
----
curl -fsSL https://get.docker.com | sh
usermod -aG docker pi

systemctl enable docker
reboot
----

Then install docker-compose using pip.
[source,bash]
----
apt update
apt -y install python3 python3-pip libffi-dev
pip3 install docker-compose

reboot
----

=== Other programs
We are currently using salt to manage our Pi's. We will install salt as well as the programs required to get the UI started.
[source,bash]
----
wget -O - https://repo.saltstack.com/apt/debian/9/armhf/archive/2018.3.2/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo "deb http://repo.saltstack.com/apt/debian/9/armhf/archive/2018.3.2 stretch main" > /etc/apt/sources.list.d/saltstack.list

apt update
apt install -y xserver-xorg xinit i3 chromium-browser tmux imagemagick x11-apps dnsmasq salt-minion ntpdate htop
apt -y upgrade
apt -y autoremove
apt -y autoclean

reboot
----

=== Pi Setup Service
We have https://github.com/byuoitav/flight-deck/tree/master/champagne[a service] to help provision new Pi's. This service that we enable in the image pulls that service down and starts it.
[source,bash]
----
mkdir /byu
curl https://raw.githubusercontent.com/byuoitav/flight-deck/master/image/pi-setup.service > /byu/pi-setup.service
curl https://raw.githubusercontent.com/byuoitav/flight-deck/master/image/pi-setup.sh > /byu/pi-setup.sh
chmod +x /byu/pi-setup.sh

systemctl daemon-reload
systemctl enable /byu/pi-setup.service
----

=== Final steps
To keep the image as small as possible, clear the commmand history.
[source,bash]
----
history -c
shutdown -h now
----

== Create a new image
Now that we have an SD card with the OS in the state we want it, we need to create an image based on that state. To start, plug the SD card into your computer.
WARNING: Copying the image from an SD card will require the same amount of storage as the _size_ of the SD card. For example, a 32GB SD card will require at least 32GB of free space.

=== Take the image
Once the SD card is plugged into your computer, use `lsblk` to figure out where the SD card is mounted.
[source,bash]
----
sudo dd if=/dev/sdb of=/path/to/clone.img <1>
----
<1> Replace `/dev/sdb` with the mount location of the SD card, and the `of=` to the location you want the image to go

=== Shrink image
Right now, the image matches the size of the SD card; A lot of that space is wasted. https://github.com/Drewsif/PiShrink[Pi Shrink] is a script that will cut out that useless space.
IMPORTANT: Always be careful downloading and running scripts, especially as sudo.

[source,bash]
----
curl https://raw.githubusercontent.com/Drewsif/PiShrink/master/pishrink.sh > pishrink.sh
chmod +x pishrink.sh
sudo ./pishrink.sh /path/to/clone.img /path/to/shrunk-image.img <1>
----

[TIP]
====
If you need to make small changes to the image _after_ you have already taken it:

. Get the start blocks with `fdisk -l /path/to/shrunk-image.img`
+
....
Disk byuav-2019-08-21.img: 3.56 GiB, 3809141248 bytes, 7439729 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: dos
Disk identifier: 0xfd9cf439

Device                Boot  Start     End Sectors  Size Id Type
byuav-2019-08-21.img1        8192  532480  524289  256M  c W95 FAT32 (LBA)
byuav-2019-08-21.img2      540672 7439728 6899057  3.3G 83 Linux
....
. Create directories in `/mnt` to mount each block to (i.e., `mkdir /mnt/piroot`)
. Mount the block(s) you want to modify, using the start sector from above. In this case, to mount the second block to `/mnt/piroot`, I would use this command:
+
	mount -v -o offset=$((512*540672)) -t ext4 byuav-2019-08-21.img `/mnt/piroot`
. Modify the images files however you need by adding/modifying/deleting files from `/mnt/piroot`
. Unmount the block(s)
	umount /mnt/piroot
====

=== Compress image
To have the smallest image size, use gzip to compress the shrunk image before sharing it.
[source,bash]
----
gzip -k -9 /path/to/shrunk-image.img
----
